steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/airy-charge-454919-p2/social-backend-app:v8', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/airy-charge-454919-p2/social-backend-app:v8']

  - name: 'gcr.io/cloud-builders/kubectl'
    args:
      - 'apply'
      - '-f'
      - 'db_secret.yaml'
      - '-f'
      - 'dev-db-deployment.yaml'
      - '-f'
      - 'dev-db-service.yaml'
      - '-f'
      - 'dev-deployment.yaml'
      - '-f'
      - 'dev-service.yaml'
    env:
      - 'CLOUDSDK_COMPUTE_REGION=us-central1-a'
      - 'CLOUDSDK_CONTAINER_CLUSTER=dev-cluster'

images:
  - 'gcr.io/airy-charge-454919-p2/social-backend-app:v8'

options:
  logging: 'CLOUD_LOGGING_ONLY'
  default_logs_bucket_behavior: 'REGIONAL_USER_OWNED_BUCKET'



