apiVersion: v1
kind: Secret
metadata:
  name: db-credentials-dev
type: Opaque
stringData:
  DB_DRIVER: "mysql+pymysql"
  DB_HOST: "127.0.0.1"
  DB_PORT: "3306"
  DB_USERNAME: "root"
  DB_PASSWORD: "admin"
  DB_DATABASE: "my_database"
