apiVersion: v1
apiVersion: v1
kind: Service
metadata:
  name: dev-web-service
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - name: frontend
      protocol: TCP
      port: 80         # External port for the frontend container
      targetPort: 80   # Container port for Nginx (frontend)
    - name: backend
      protocol: TCP
      port: 8080       # External port for backend access
      targetPort: 8000 # Container port for the backend API
