apiVersion: v1
kind: Service
metadata:
  name: dev-web-service
spec:
  type: LoadBalancer
  selector:
    app: dev-combined-app
  ports:
    - protocol: TCP
      port: 80         # External port
      targetPort: 80 # Web container listens on 80
