apiVersion: apps/v1
kind: Deployment
metadata:
  name: dev-web-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: backend-container
          image: gcr.io/airy-charge-454919-p2/social-backend-app:v11
          ports:
            - containerPort: 8000
          # Use environment variables and secrets as before
          env:
            - name: DB_HOST
              value: "dev-db-service"
          envFrom:
            - secretRef:
                name: db-credentials-dev
        - name: frontend-container
          image: gcr.io/airy-charge-454919-p2/social-frontend-app:v1
          ports:
            - containerPort: 80