apiVersion: apps/v1
kind: Deployment
metadata:
  name: prod-web-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: prod-backend
  template:
    metadata:
      labels:
        app: prod-backend
    spec:
      nodeSelector:
        role: web-server
      containers:
        - name: backend-container
          image: gcr.io/airy-charge-454919-p2/social-backend-app:v14
          ports:
            - containerPort: 8000
          envFrom:
            - secretRef:
                name: db-credentials-prod
        - name: frontend-container
          image: gcr.io/airy-charge-454919-p2/social-frontend-app:v5
          ports:
            - containerPort: 80