apiVersion: v1
kind: Service
metadata:
  name: prod-service
spec:
  type: LoadBalancer
  selector:
    app: prod-backend
  ports:
    - name: frontend
      protocol: TCP
      port: 80         # For frontend traffic
      targetPort: 80
    - name: backend
      protocol: TCP
      port: 8080       # For backend traffic
      targetPort: 8000
